spring.application.name=Jobhook
spring.data.mongodb.auto-index-creation = true
spring.data.mongodb.uri=mongodb://localhost:27017/jobportal1

#Email service properties
spring.mail.host =smtp.gmail.com
spring.mail.port = 587
spring.mail.username=fraudshield49@gmail.com
spring.mail.password=hokdbivvynydtdnw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#User service messages
USER_FOUND = User has already registered with the email id
NOT_FOUND = User is not registered with the email id
INVALID_CREDENTIALS = Invalid password or email
OTP_NOT_FOUND = OTP is expired
INVALID_OTP = OTP must be 6 digits
INCORRECT_OTP = OTP is incorrect.
INCORRECT_OLD_PASSWORD= Incorrect old password.